create table professor(
codigo int primary key auto_increment,
nome varchar(60) not null,
formacao varchar(100) not null);


INSERT INTO professor (nome, formacao) VALUES 
('Ana Souza', 'Pedagogia'),
('Carlos Oliveira', 'Engenharia Civil'),
('Juliana Santos', 'Direito'),
('Marcelo Silva', 'Administração'),
('Fernanda Pereira', 'Medicina'),
('José Costa', 'Engenharia Elétrica'),
('Maria Rocha', 'Psicologia'),
('Lucas Almeida', 'Arquitetura'),
('Amanda Lima', 'Jornalismo'),
('Rafael Pereira', 'Tecnologia da Informação'),
('Cláudia Barbosa', 'Pedagogia'),
('Thiago Martins', 'Física'),
('Sofia Alves', 'Matemática'),
('Bruna Costa', 'Design Gráfico'),
('Paulo Gonçalves', 'Engenharia Mecânica'),
('Carla Oliveira', 'Enfermagem'),
('Ricardo Lima', 'Administração'),
('Gabriela Souza', 'Publicidade e Propaganda'),
('Felipe Silva', 'Direito'),
('Tatiane Gomes', 'Medicina'),
('Bruno Almeida', 'Engenharia Química'),
('Aline Rocha', 'História'),
('Vitor Santos', 'Gestão de Recursos Humanos'),
('Isabela Oliveira', 'Biologia'),
('Eduardo Lima', 'Ciência da Computação'),
('Camila Martins', 'Filosofia'),
('André Costa', 'Engenharia de Software'),
('Luana Pereira', 'Nutrição'),
('Raul Rocha', 'Engenharia Elétrica'),
('Simone Santos', 'Pedagogia'),
('Gustavo Silva', 'Medicina Veterinária'),
('Renata Oliveira', 'Química'),
('Luiz Santos', 'Administração'),
('Roberta Almeida', 'Artes Cênicas'),
('Marcos Costa', 'Tecnologia da Informação'),
('Jéssica Souza', 'Biomedicina'),
('João Pedro Santos', 'Engenharia Ambiental'),
('Carolina Pereira', 'Arquitetura e Urbanismo'),
('Rodrigo Lima', 'Engenharia Mecânica'),
('Lúcia Alves', 'Direito'),
('Matheus Barbosa', 'Economia'),
('Vanessa Rocha', 'Enfermagem'),
('Ricardo Martins', 'Publicidade e Propaganda'),
('Helena Costa', 'Psicologia'),
('Bruno Souza', 'Educação Física'),
('Tatiane Oliveira', 'Geografia'),
('Fábio Almeida', 'Contabilidade'),
('Michele Santos', 'Administração'),
('Cássio Lima', 'Relações Internacionais'),
('Mariana Silva', 'História'),
('Fábio Costa', 'Ciência da Computação'),
('Aline Pereira', 'Medicina'),
('Carlos Martins', 'Engenharia de Produção'),
('Patrícia Rocha', 'Pedagogia'),
('Eduardo Santos', 'Administração'),
('Robson Oliveira', 'Arquitetura'),
('Gisele Lima', 'Jornalismo'),
('Juliano Costa', 'Engenharia Civil'),
('Elaine Barbosa', 'Nutrição'),
('Fernando Almeida', 'Tecnologia da Informação'),
('Larissa Silva', 'Direito'),
('Gustavo Oliveira', 'Psicologia'),
('Natália Souza', 'Matemática'),
('Diana Pereira', 'Enfermagem'),
('Anderson Santos', 'Administração'),
('Raquel Lima', 'Filosofia'),
('Juliano Alves', 'Medicina'),
('Carlos Gomes', 'Engenharia Elétrica'),
('Ricardo Barbosa', 'Relações Internacionais'),
('Tatiane Almeida', 'Enfermagem'),
('Márcia Costa', 'Ciência da Computação'),
('Cristina Lima', 'Engenharia Mecânica'),
('Nádia Santos', 'História'),
('Alexandre Rocha', 'Engenharia Química'),
('Gabriela Souza', 'Pedagogia'),
('Márcio Lima', 'Jornalismo'),
('Vera Oliveira', 'Psicologia'),
('Silvia Almeida', 'Direito'),
('Felipe Costa', 'Administração'),
('Camila Souza', 'Matemática'),
('Henrique Lima', 'Economia'),
('Renato Rocha', 'Filosofia'),
('Paula Alves', 'Pedagogia'),
('Eduardo Barbosa', 'Enfermagem'),
('José Martins', 'Administração'),
('Diana Lima', 'Ciência da Computação'),
('Marcelo Pereira', 'Engenharia de Produção'),
('Patrícia Souza', 'Artes Cênicas'),
('Lucas Oliveira', 'Física'),
('Larissa Silva', 'Publicidade e Propaganda'),
('Roberto Lima', 'Medicina Veterinária'),
('Carla Santos', 'Psicologia'),
('Rogério Rocha', 'Ciência da Computação'),
('Gabriela Almeida', 'Engenharia Civil'),
('Eduardo Costa', 'Jornalismo'),
('Daniele Lima', 'Pedagogia'),
('Raul Oliveira', 'Química'),
('Vanessa Souza', 'Filosofia'),
('Gustavo Lima', 'Medicina'),
('Paula Rocha', 'Administração'),
('Bruna Lima', 'Enfermagem'),
('Alexandre Silva', 'Matemática'),
('Tatiane Gomes', 'Arquitetura'),
('Lucas Costa', 'Engenharia Elétrica'),
('Carlos Lima', 'Psicologia'),
('Amanda Pereira', 'Publicidade e Propaganda'),
('Joana Souza', 'Direito'),
('Lucas Barbosa', 'Engenharia de Produção'),
('João Oliveira', 'Biologia'),
('Simone Lima', 'Relações Internacionais'),
('Tiago Rocha', 'Ciência da Computação'),
('Sílvia Barbosa', 'Pedagogia'),
('Luiz Costa', 'Administração');
